version: '3.8'

services:
    php-fpm:
        build:
            context: .
            dockerfile: .docker/php-fpm/Dockerfile
        container_name: url_shortener
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www

        depends_on:
            - mysql
            - redis

        networks:
            - url_shortener

    nginx:
        image: nginx:alpine
        container_name: nginx_url_shortener
        restart: unless-stopped
        ports:
            - "8080:80"

        volumes:
            - .:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
            - mysql

        networks:
            - url_shortener

    mysql:
        image: mysql:8
        container_name: url_shortener_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'

        volumes:
            - db_data:/var/lib/mysql

        ports:
            - "3306:3306"

        networks:
            - url_shortener

    redis:
        image: redis:alpine
        container_name: url_shortener_redis
        restart: unless-stopped
        networks:
            - url_shortener

networks:
    url_shortener:

volumes:
    db_data:
